name: heavenslive
description: HeavensLive Mobile - Marketplace + Credon Wallet
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  just_audio: ^0.9.36
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
